### ISSUE TITLE
Shell volume incorrectly scaled?

### ISSUE THREAD

**Issue by robban80** [ModelDBRepository/244848#1]
This potential error regards the file:
> modcamechs.mod

Seems like the shell volume is only scaled properly for the first substrate. Here dsqvol is updated:

`FROM i=0 TO Nannuli-1 {
	 dsqvol = dsq*vrat[i]
        ~ ca[i] + bufs[i] <-> cabufs[i]  (kfs*dsqvol, (0.001)*KDs*kfs*dsqvol)
        :~ ca[i] + bufm[i] <-> cabufm[i]  (kfm*dsqvol, (0.001)*KDm*kfm*dsqvol)
	}`

while all the following substrates are not, e.g:

`FROM i=0 TO Nannuli-1 {
     :pump
   	~ ca[i] << (-dsqvol*beta*vmax*ca[i]^2 / (ca[i]^2 + Kp^2))
     :leak
   	 ~ ca[i] << (dsqvol*beta*L[i]*(1 - (ca[i]/caer)))
        }`

**Comment by tommorse** [comment]
The authors responded to this notice by contributing a fix.  They found that although it changes their results quantitatively, they are qualitatively the same.
